### ISSUE TITLE
What is the best performance for overall quality ? Higher? Lower? And the range ?

### ISSUE THREAD

**Issue by kehuantiantang** [gabrielmittag/NISQA#21]
Thrnak you so much for your contribution. There has five speech quality dimeansons output by inference the network.  I wounder to make sure whether my understand is correct for some metrics. 
```
For better synthetic speech
MOS: higher, [0, 5]
Noiseness: lower, range ？
Coloration: higher， range ？
Discontinuity: lower, range ？
Loudness: higher, range ？
```
Thank you so much for your help. Have a nice day.

**Comment by nattaran** [comment]
I have the same question. I did not find any range and description for these quality-based parameters metrics in the repo

**Comment by gabrielmittag** [comment]
Hi,

For the overall quality MOS and the four quality dimensions the range is [1, 5] where 1 is poor quality and 5 is excellent quality. BTW - the quality dimensions (Noisiness, Coloration, Discontinuity, Loudness) cannot be used for synthetic speech. To predict the Naturalness of synthetic speech use the nisqa_tts.tar weights

Let me know if anything is still unclear.

Best,
Gabriel

**Comment by StianHanssen** [comment]
@gabrielmittag Hi, sorry to bring this up again, but I just wanted to clarify when it comes to dimensions such as loudness. For example, if I get a 1 in loudness, does that mean the speech is too quiet, or does it mean the audio is so loud that it is peaking which is bad in a different way?

For noisiness, coloration and discontinuity I take it that we have less of each the closer to 5 we have. I.e. an audio clip that is not very noisy is closer to 5.

**Comment by gabrielmittag** [comment]
Hi, 

That's correct for noisiness, coloration and discontinuity. For Loudness the score represents how optimal the loudness is, that means a sample with non-optimal loudness (either too loud or too quiet) will be rated with a lower score.

Here is a brief explanation of the different dimensions:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/33029509/235495151-1f612b23-d88e-4584-b887-cf531484e0ec.png">

The following graph shows the average loudness predictions of the model vs the active speech level in dBov. The optimal level is around -26 dBov because most samples in the dataset were normalized for that level (apart from the ones with non-optimal loudness on purpose).
<img width="465" alt="image" src="https://user-images.githubusercontent.com/33029509/235496639-5ba8eb99-d3cc-4685-a344-096d1e312330.png">

Figure source: https://link.springer.com/book/10.1007/978-3-030-91479-0
