### ISSUE TITLE
NISQA Double Ended pretrained weights?

### ISSUE THREAD

**Issue by naba89** [gabrielmittag/NISQA#7]
Hi,

I am sorry if I have missed it somehow, but may I know how to use the double ended NISQA model for quality assessment with reference signal?

Best regards
Nabarun

**Comment by gabrielmittag** [comment]
Hi,

You can use the "train_nisqa_double_ended.yaml" to train a new double-ended model. There are no double-ended model weights made available because, in our experiments, the prediction performance of the available single-ended model was almost similar to the double-ended model after we added more data.

Best.
Gabriel

**Comment by naba89** [comment]
Thank you so much for your reply. I understand.
